# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'open'), (1, 'closed')], max_length=1),
        ),
    ]
